### ISSUE TITLE
KeyError: 'pretty_type'

### ISSUE THREAD

**Issue by Xarlos89** [ErikKalkoken/slackchannel2pdf#11]
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\slackchannel2pdf-1.0.0\slackchannel2pdf\run.py", line 196, in <module>
    main()
  File "C:\Users\USER\Desktop\slackchannel2pdf-1.0.0\slackchannel2pdf\run.py", line 183, in main
    exporter.run(
  File "C:\Users\USER\Desktop\slackchannel2pdf-1.0.0\slackchannel2pdf\slackchannel2pdf.py", line 1585, in run
    self._write_messages_to_pdf(document, messages, threads)
  File "C:\Users\USER\Desktop\slackchannel2pdf-1.0.0\slackchannel2pdf\slackchannel2pdf.py", line 1216, in _write_messages_to_pdf
    last_user_id = self._parse_message_and_write_to_pdf(
  File "C:\Users\USER\Desktop\slackchannel2pdf-1.0.0\slackchannel2pdf\slackchannel2pdf.py", line 931, in _parse_message_and_write_to_pdf
    + file["pretty_type"]
KeyError: 'pretty_type'

**Comment by ErikKalkoken** [comment]
Thanks for opening the issue. Could you please provide an example of the message that is causing this error in JSON? Then I can try to recreate and fix this bug. You can do this with the argument `--write-raw-data`

See also our discussion in #3

**Comment by davidbsp** [comment]
Hi @ErikKalkoken, I'm also getting this bug. Here is the output of running the command with a token on a channel in my workspace:

```
Fetched a total of 10.000 messages from channel
Fetching messages from thread 1 - page 1
Fetched a total of 2 messages from 1 threads
Fetching names for 3 bots
Writing file: name .\SEMFIRE ISR-UC Perception Team_users.json
Writing file: name .\SEMFIRE ISR-UC Perception Team_bots.json
Writing file: name .\SEMFIRE ISR-UC Perception Team_channels.json
Writing file: name .\SEMFIRE ISR-UC Perception Team_usergroups.json
Writing file: name .\SEMFIRE ISR-UC Perception Team_fruc_cmu_portugal_mapping_path_planning_messages.json
Writing file: name .\SEMFIRE ISR-UC Perception Team_fruc_cmu_portugal_mapping_path_planning_threads.json
Traceback (most recent call last):
  File "run.py", line 196, in <module>
  File "run.py", line 191, in main
  File "slackchannel2pdf.py", line 1584, in run
  File "slackchannel2pdf.py", line 1219, in _write_messages_to_pdf
  File "slackchannel2pdf.py", line 934, in _parse_message_and_write_to_pdf
KeyError: 'pretty_type'
[3520] Failed to execute script run
```

Which of JSON files do you want me to send you?

**Comment by ErikKalkoken** [comment]
Hey David!

That looks like an easy bug to fix. Please send me the last JSON file
mentioned before the exception:

SEMFIRE ISR-UC Perception
Team_fruc_cmu_portugal_mapping_path_planning_threads.json


Cheers,
Erik
