### ISSUE TITLE
KeyError: 'team'

### ISSUE THREAD

**Issue by Neznakomec** [ErikKalkoken/slackchannel2pdf#17]
Exporting channel from Slack...
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\slackchannel2pdf.exe\__main__.py", line 7, in <module>
  File "C:\Anaconda3\lib\site-packages\slackchannel2pdf\cli.py", line 79, in main
    exporter = SlackChannelExporter(
  File "C:\Anaconda3\lib\site-packages\slackchannel2pdf\channel_exporter.py", line 71, in __init__
    self._slack_service = SlackService(slack_token)
  File "C:\Anaconda3\lib\site-packages\slackchannel2pdf\slack_service.py", line 34, in __init__
    logger.info("Current Slack workspace: %s", self.team)
  File "C:\Anaconda3\lib\site-packages\slackchannel2pdf\slack_service.py", line 75, in team
    return self._workspace_info["team"]
KeyError: 'team'

**Comment by Neznakomec** [comment]
It seems I can't create a token with all the permissions required.
Slack offers to create App Token only

**Comment by ErikKalkoken** [comment]
Should be fixed with 1.5.1. Would be awesome if you could check and conform if the fix worked for you.
