### ISSUE TITLE
Cannot install on macOS

### ISSUE THREAD

**Issue by JakubKubista** [ErikKalkoken/slackchannel2pdf#2]
I end up with following issue:
```
Collecting slackchannel2pdf
  Downloading slackchannel2pdf-1.1.2.tar.gz (1.2 MB)
     |████████████████████████████████| 1.2 MB 5.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-tysmb0/slackchannel2pdf/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-tysmb0/slackchannel2pdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-ASdHcr
         cwd: /private/tmp/pip-install-tysmb0/slackchannel2pdf/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-tysmb0/slackchannel2pdf/setup.py", line 9, in <module>
        with open(os.path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Following solution should work: https://github.com/asweigart/PyGetWindow/issues/9

**Comment by ErikKalkoken** [comment]
Sorry for the extremely late reply, but the reason for your issue is that you are using Python 2. However, this app requires Python 3.

**Comment by JakubKubista** [comment]
No worries. Thank you for the reply. I will try it for the next time and maybe share some forks.
