### ISSUE TITLE
Error 'pretty type' - cant' export slack channel to pdf 

### ISSUE THREAD

**Issue by Lionheart-Crow** [ErikKalkoken/slackchannel2pdf#3]
When trying to download the conversation from one channel I get the following result:

```
Fetched a total of 1,141 messages from 252 threads
Traceback (most recent call last):
  File "c:\users\fgh\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\fgh\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\fgh\anaconda3\Scripts\slackchannel2pdf.exe\__main__.py", line 7, in <module>
  File "c:\users\fgh\anaconda3\lib\site-packages\slackchannel2pdf\run.py", line 190, in main
    exporter.run(
  File "c:\users\fgh\anaconda3\lib\site-packages\slackchannel2pdf\slackchannel2pdf.py", line 1519, in run
    self._write_messages_to_pdf(document, messages, threads)
  File "c:\users\fgh\anaconda3\lib\site-packages\slackchannel2pdf\slackchannel2pdf.py", line 1156, in _write_messages_to_pdf
    last_user_id = self._parse_message_and_write_to_pdf(
  File "c:\users\fgh\anaconda3\lib\site-packages\slackchannel2pdf\slackchannel2pdf.py", line 870, in _parse_message_and_write_to_pdf
    + file["pretty_type"]
KeyError: 'pretty_type'
```

**Comment by ErikKalkoken** [comment]
I deployed a new version (1.1.4) that should be able to handle a missing `pretty_type`.

Would be great if you could retest and five me feedback if the fix works for you. Thanks!

**Comment by ErikKalkoken** [comment]
User confirmed the bug is fixed

**Comment by Xarlos89** [comment]
Also ran into this issue. I see there is a fix available. The project is on 1.1.3, where can we find 1.1.4?
