### ISSUE TITLE
RuntimeError("<s> tags can not be nested")

### ISSUE THREAD

**Issue by wfuchs** [ErikKalkoken/slackchannel2pdf#6]
Hello, i get the following error when i try to fetch my Slack general channel.
I have tested it under Windows 10 Python 3.9.1 and Linux Ubuntu 18.04 Python 3.6.9
both same error

```C:\Users\PC\AppData\Local\Programs\Python\Python39\Scripts\slackchannel2pdf.exe --token xoxp-*** general
slackchannel2pdf v1.2.4 by Erik Kalkoken

[INFO] Fetching workspace info from Slack...
[INFO] Current Slack workspace: Slack-Demo
[INFO] Fetching users from workspace...
[INFO] Fetching users from workspace... - page 2
[INFO] Fetching users from workspace... - page 3
[INFO] Fetching users from workspace... - page 4
[INFO] Fetching users from workspace... - page 5
[INFO] Fetching users from workspace... - page 6
[INFO] Fetching users from workspace... - page 7
[INFO] Fetching users from workspace... - page 8
[INFO] Fetching users from workspace... - page 9
[INFO] Fetching users from workspace... - page 10
[INFO] Fetching users from workspace... - page 11
[INFO] Fetching users from workspace... - page 12
[INFO] Fetching users from workspace... - page 13
[INFO] Fetching users from workspace... - page 14
[INFO] Fetching users from workspace... - page 15
[INFO] Fetching users from workspace... - page 16
[INFO] Fetching users from workspace... - page 17
[INFO] Fetching users from workspace... - page 18
[INFO] Fetching users from workspace... - page 19
[INFO] Fetching users from workspace... - page 20
[INFO] Fetching users from workspace... - page 21
[INFO] Received 4,096 users
[INFO] Current Slack user: Demo
[INFO] Fetching channels from workspace...
[INFO] Received 7 channels
[INFO] Fetching usergroups from Slack...
[INFO] This workspace has no usergroups
[INFO] Fetching user info for author...
[INFO] Locale is: English (United States) [en_US]
[INFO] Timezone is: Europe/Amsterdam
[INFO] Writing output to: C:\slack
[INFO] Page orientation: Portrait
[INFO] Page format: A4
[INFO] Current channel : general
[INFO] Fetching messages from channel...
[INFO] Fetching messages from channel... - page 2
[INFO] Fetching messages from channel... - page 3
[INFO] Fetching messages from channel... - page 4
[INFO] Fetching messages from channel... - page 5
[INFO] Fetching messages from channel... - page 6
[INFO] Fetching messages from channel... - page 7
[INFO] Fetching messages from channel... - page 8
[INFO] Fetching messages from channel... - page 9
[INFO] Fetching messages from channel... - page 10
[INFO] Fetching messages from channel... - page 11
[INFO] Fetching messages from channel... - page 12
[INFO] Fetching messages from channel... - page 13
[INFO] Fetching messages from channel... - page 14
[INFO] Received 2,611 messages
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Fetching threads from channel...
[INFO] Received 42 messages from 14 threads
Traceback (most recent call last):
  File "c:\users\PC\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\PC\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python39\Scripts\slackchannel2pdf.exe\__main__.py", line 7, in <module>
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\run.py", line 90, in main
    exporter.run(
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\channel_exporter.py", line 882, in run
    self._write_messages_to_pdf(document, messages, threads)
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\channel_exporter.py", line 537, in _write_messages_to_pdf
    last_user_id = self._parse_message_and_write_to_pdf(
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\channel_exporter.py", line 188, in _parse_message_and_write_to_pdf
    document.write_html(
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\fpdf_ext.py", line 85, in write_html
    self._open_tag(tag, attributes)
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\fpdf_ext.py", line 104, in _open_tag
    raise RuntimeError("<s> tags can not be nested")
RuntimeError: <s> tags can not be nested```

**Comment by ErikKalkoken** [comment]
Hey, thanks for reporting this bug. This looks like you have nested code formatting in your messages, which is currently not supported (also does not make much sense semantically). I can look into finding workaround for this, so the export does at least not break.

**Comment by ErikKalkoken** [comment]
Sadly I was not able to reproduce your issue, so now I please need your help. 

As a workaround I improved the error handling, so now the export will no longer abort when this issue is encountered. Instead an error is logged and the text with the issue will be discarded.

To better understand what causes this issue, I would please need the exact text of that error message. 
In addition it would be helpful if you could store the raw data of your channel and provide me with the exact message that causes this issue. Just pass `--write-raw-data` when running the export and the app will store all messages in a JSON file.

Please use this new version: https://pypi.org/project/slackchannel2pdf/1.3.0a3/

**Comment by wfuchs** [comment]
Sorry for the long delay. In the Slack are about 2000 posts a day and the Error was gone.
Now it occurs again.
I downloaded the 1.3.0a3 and the error comes as follows:
```
C:\Users\%username%\AppData\Local\Programs\Python\Python39\Scripts\slackchannel2pdf.exe --write-raw-data --token xoxp-***** general
Exporting channel from Slack...
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\fpdf_ext.py", line 90, in write_html
    self._open_tag(tag, attributes)
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\fpdf_ext.py", line 112, in _open_tag
    raise HtmlConversionError("<s> tags can not be nested")
slackchannel2pdf.fpdf_ext.HtmlConversionError: <s> tags can not be nested

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\PC\appdata\local\programs\python\python39\lib\logging\__init__.py", line 1079, in emit
    msg = self.format(record)
  File "c:\users\PC\appdata\local\programs\python\python39\lib\logging\__init__.py", line 923, in format
    return fmt.format(record)
  File "c:\users\PC\appdata\local\programs\python\python39\lib\logging\__init__.py", line 659, in format
    record.message = record.getMessage()
  File "c:\users\PC\appdata\local\programs\python\python39\lib\logging\__init__.py", line 363, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "c:\users\PC\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\PC\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python39\Scripts\slackchannel2pdf.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\cli.py", line 90, in main
    result = exporter.run(
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\channel_exporter.py", line 884, in run
    self._write_messages_to_pdf(document, messages, threads)
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\channel_exporter.py", line 539, in _write_messages_to_pdf
    last_user_id = self._parse_message_and_write_to_pdf(
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\channel_exporter.py", line 190, in _parse_message_and_write_to_pdf
    document.write_html(
  File "c:\users\PC\appdata\local\programs\python\python39\lib\site-packages\slackchannel2pdf\fpdf_ext.py", line 93, in write_html
    logger.error("Failed to convert HTML to PDF:", html)
Message: 'Failed to convert HTML to PDF:'
Arguments: ('I rarely/never see <s fontfamily="NotoSansMono">pickup_offset=7</s> successfully picking up a item. Usually takes needs to fully reset after to pick, so I figured less time-wasting trying to offset might fix that',)
written: Demo_general.pdf
```

In the Demo_general_messages.json is the following code
```
    {
        "blocks": [
            {
                "block_id": "QLA",
                "elements": [
                    {
                        "elements": [
                            {
                                "text": "I rarely/never see ",
                                "type": "text"
                            },
                            {
                                "style": {
                                    "code": true
                                },
                                "text": "pickup_offset=7",
                                "type": "text"
                            },
                            {
                                "text": " successfully picking up a item. Usually takes needs to fully reset after to pick, so I figured less time-wasting trying to offset might fix that",
                                "type": "text"
                            }
                        ],
                        "type": "rich_text_section"
                    }
                ],
                "type": "rich_text"
            }
        ],
        "client_msg_id": "c8eda14f-acf8-41e4-bcae-caf282d42c24",
        "team": "TB133EHR8",
        "text": "I rarely/never see `pickup_offset=7` successfully picking up a item. Usually takes needs to fully reset after to pick, so I figured less time-wasting trying to offset might fix that",
        "ts": "1614075414.168100",
        "type": "message",
        "user": "U417REP7CE1"
    },
```
I hope this helps to remove this error completely.

**Comment by ErikKalkoken** [comment]
No worries and thank you for the info. This should hopefully allow me to reproduce the error and fix it. I'll keep you posted!

**Comment by ErikKalkoken** [comment]
Sorry, for the super late reply. I got side-tracked on another projects.

I have include your example in my test, but sadly, I was not able to re-produce the issue with your example.
